spring:
  #  application:
  #    name: study

  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: 8202
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#  sql:
#    init:
#      mode: never
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        hbm2ddl:
#          auto: create
#        default_batch_fetch_size: 1000


server:
  port: 9090

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace